### PR TITLE
fix(users): user ids don't always start_with table_name

### PR DESCRIPTION
**Pull request by stakach**

### CODE REVIEW

**Comment by caspiano** [comment]
Are there any examples for cases where the id doesn't start with the table name?

**Comment by stakach** [comment]
all SSO users on all deployments as the id generation on Ruby NoBrainer is different

**Comment by caspiano** [comment]
Cool, I’ll take note of that

**Comment by stakach** [comment]
all good, @w-le noticed it tonight, simple fix

**Pull request merged**
