### PR TITLE
fix(modules): [PPT-32] search query

### PR DESCRIPTION
**Pull request by chillfox**

### CODE REVIEW

**Review by stakach — APPROVED** [review]
LGTM

**Comment by stakach** [comment]
would have approved earlier but wasn't sure about this issue with the spec runner
image

**Comment by chillfox** [comment]
The `http.cors.enabled: true` docker-compose error might just be down to different versions.

**Comment by chillfox** [comment]
@stakach looks like we have tests that change behaviour depending upon other tests...
If I run `./test --tag search` then it passes, but if running the full specs then it fails (including search tagged tests).

**Comment by chillfox** [comment]
yeah, specs that fail on Github are different to the tests failing locally

**Comment by chillfox** [comment]
clearing the DB before each test results in even more tests failing...

**Comment by chillfox** [comment]
```cr
def random_name
  UUID.random.to_s.split('-').first
end
```

might not be random enough to just use the first bit of the uuid

**Pull request merged**
